"""Initialize tables

Revision ID: d21d942d992f
Revises: 
Create Date: 2025-09-15 14:11:17.753214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21d942d992f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('species', sa.String(length=100), nullable=False),
    sa.Column('dates_captured', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_id'), 'plants', ['id'], unique=False)
    op.create_table('morphology_timeline',
    sa.Column('plant_id', sa.String(length=50), nullable=False),
    sa.Column('date_captured', sa.Date(), nullable=False),
    sa.Column('size_area', sa.Float(), nullable=False),
    sa.Column('size_convex_hull_area', sa.Float(), nullable=False),
    sa.Column('size_solidity', sa.Float(), nullable=False),
    sa.Column('size_perimeter', sa.Float(), nullable=False),
    sa.Column('size_width', sa.Float(), nullable=False),
    sa.Column('size_height', sa.Float(), nullable=False),
    sa.Column('size_longest_path', sa.Float(), nullable=False),
    sa.Column('size_center_of_mass', sa.JSON(), nullable=False),
    sa.Column('size_convex_hull_vertices', sa.JSON(), nullable=False),
    sa.Column('size_ellipse_center', sa.JSON(), nullable=False),
    sa.Column('size_ellipse_major_axis', sa.Float(), nullable=False),
    sa.Column('size_ellipse_minor_axis', sa.Float(), nullable=False),
    sa.Column('size_ellipse_angle', sa.Float(), nullable=False),
    sa.Column('size_ellipse_eccentricity', sa.Float(), nullable=False),
    sa.Column('size_num_leaves', sa.Integer(), nullable=False),
    sa.Column('size_num_branches', sa.Integer(), nullable=False),
    sa.Column('morph_branch_pts', sa.JSON(), nullable=False),
    sa.Column('morph_tips', sa.JSON(), nullable=False),
    sa.Column('morph_segment_path_length', sa.JSON(), nullable=False),
    sa.Column('morph_segment_eu_length', sa.JSON(), nullable=False),
    sa.Column('morph_segment_curvature', sa.JSON(), nullable=False),
    sa.Column('morph_segment_angle', sa.JSON(), nullable=False),
    sa.Column('morph_segment_tangent_angle', sa.JSON(), nullable=False),
    sa.Column('morph_segment_insertion_angle', sa.JSON(), nullable=False),
    sa.Column('morphology_image_key', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('plant_id', 'date_captured')
    )
    op.create_table('processed_data',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('plant_id', sa.String(length=50), nullable=False),
    sa.Column('image_key', sa.String(length=255), nullable=True),
    sa.Column('date_processed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_captured', sa.Date(), nullable=False),
    sa.Column('vegetation_features', sa.JSON(), nullable=True),
    sa.Column('morphology_features', sa.JSON(), nullable=True),
    sa.Column('texture_features', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'date_captured', name='_unique_plant_image_per_day')
    )
    op.create_index(op.f('ix_processed_data_id'), 'processed_data', ['id'], unique=False)
    op.create_index(op.f('ix_processed_data_plant_id'), 'processed_data', ['plant_id'], unique=False)
    op.create_table('texture_timeline',
    sa.Column('plant_id', sa.String(length=50), nullable=False),
    sa.Column('date_captured', sa.Date(), nullable=False),
    sa.Column('band_name', sa.String(length=20), nullable=False),
    sa.Column('texture_type', sa.String(length=20), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('std', sa.Float(), nullable=False),
    sa.Column('q25', sa.Float(), nullable=False),
    sa.Column('q75', sa.Float(), nullable=False),
    sa.Column('min', sa.Float(), nullable=False),
    sa.Column('max', sa.Float(), nullable=False),
    sa.Column('texture_image_key', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('plant_id', 'date_captured', 'band_name', 'texture_type')
    )
    op.create_table('vegetation_index_timeline',
    sa.Column('plant_id', sa.String(length=50), nullable=False),
    sa.Column('date_captured', sa.Date(), nullable=False),
    sa.Column('index_type', sa.String(length=20), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('std', sa.Float(), nullable=False),
    sa.Column('q25', sa.Float(), nullable=False),
    sa.Column('q75', sa.Float(), nullable=False),
    sa.Column('min', sa.Float(), nullable=False),
    sa.Column('max', sa.Float(), nullable=False),
    sa.Column('index_image_key', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('plant_id', 'date_captured', 'index_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vegetation_index_timeline')
    op.drop_table('texture_timeline')
    op.drop_index(op.f('ix_processed_data_plant_id'), table_name='processed_data')
    op.drop_index(op.f('ix_processed_data_id'), table_name='processed_data')
    op.drop_table('processed_data')
    op.drop_table('morphology_timeline')
    op.drop_index(op.f('ix_plants_id'), table_name='plants')
    op.drop_table('plants')
    # ### end Alembic commands ###
